;<?/* this prevents browsers from seeing anything

;authentication server connection information
[authserver]
host="localhost:8088"
path="/xmlrpc"

;optional seperate server for outbound notifications
[dmapidb]
persistent=true
host="localhost"
user="root"
pass=""
db="dmapi"

;shard/customer db for redialer to execute generatejobsql.php
[redialer]
host="localhost"
user="root"
pass=""
; only set db for commsuite, otherwise its generated by "c_".customerid
;db="commsuite"

[feature]
is_commsuite=false
; commsuite users may need to disable the inbound number verification
; if true, only validates user/pass and not inbound phone number
disable_inbound_number_verification=false
has_ssl=true
force_ssl=false
log_dir="/commsuite/logs/"
log_db_errors=true
log_db_queries=true
log_dmapi=true
has_print=true
tmp_dir="/tmp"
has_sms=true

;if not set, warn_earliest is set to "7:00 am"
;and warn_latest is set to "9:00 pm"
warn_earliest=
warn_latest=

[content]
;tts="devbox4,8080,/phone/Tts"
tts="10.25.25.15,8080,/tts/ttsloquendo"

externalcontent=false
; format is "host,port,path;host2,port2,path2;..." reserved chars= ';' and ','
get="localhost,80,/foobar/xxx-get.php"
put="localhost,80,/foobar/xxx-put.php"


[ldap]
is_ldap=false
ldapconnect="192.168.174.2"
ldapusername="user"
ldappassword="pass"

; cn is the directory where ldap users live ex. "users" or "teachers"
; ad and com make up the domain
; ex. if their domain/ldap extension is @adtest.net then
; ldap_ad = "adtest" and ldap_com="net"
ldap_cn="users"
ldap_ad="adtest"
ldap_com="net"

;*/?>
