<?
//Color schemes.inc.php

$COLORSCHEMES =  array(
					"classroom" => array("displayname" => "Classroom",
											"_brandprimary" => "3e693f",
											"_brandtheme1" => "3e693f",
											"_brandtheme2" => "b47727",
											"_brandratio" => ".2"),
					"3dblue" => array("displayname" => "3D - Blue",
											"_brandprimary" => "26477D",
											"_brandtheme1" => "89A3CE",
											"_brandtheme2" => "89A3CE",
											"_brandratio" => ".3"),
					"rose" =>	array("displayname" => "3D - Rose",
											"_brandprimary" => "740606",
											"_brandtheme1" => "BE0101",
											"_brandtheme2" => "BE0101",
											"_brandratio" => ".35"),
					"gold" =>	array("displayname" => "3D - Gold",
											"_brandprimary" => "654000",
											"_brandtheme1" => "E9B500",
											"_brandtheme2" => "E9B500",
											"_brandratio" => ".3"),
					"lemon" =>	array("displayname" => "3D - Lemon",
											"_brandprimary" => "654000",
											"_brandtheme1" => "E9B500",
											"_brandtheme2" => "E9B500",
											"_brandratio" => ".3"),
					"tangerine" =>	array("displayname" => "3D - Tangerine",
											"_brandprimary" => "291300",
											"_brandtheme1" => "FE8C0D",
											"_brandtheme2" => "FE8C0D",
											"_brandratio" => ".3"),
					"greentheme" => array("displayname" => "3D - Green",
											"_brandprimary" =>"42563B",
											"_brandtheme1" => "006400",
											"_brandtheme2" => "32CD32",
											"_brandratio" => ".3"),
					"chrome" => array("displayname" => "3D - Chrome",
											"_brandprimary" => "000000",
											"_brandtheme1" => "6F7177",
											"_brandtheme2" => "6F7177",
											"_brandratio" => "0"),

					"sm" => array("displayname" => "Classic - Silver",
											"_brandprimary" => "346799",
											"_brandtheme1" => "999999",
											"_brandtheme2" => "CCCCCC",
											"_brandratio" => "0"),
					"redmainblueback" => array("displayname" => "Classic - Tech",
											"_brandprimary" => "CC0000",
											"_brandtheme1" => "990000",
											"_brandtheme2" => "550000",
											"_brandratio" => ".1"),
					"grass" => array("displayname" => "Classic - Green",
											"_brandprimary" => "087800",
											"_brandtheme1" => "00CC00",
											"_brandtheme2" => "0c8100",
											"_brandratio" => ".3"),
					"mintgreen" => array("displayname" => "Classic - Key Lime",
											"_brandprimary" => "009900",
											"_brandtheme1" => "1CBF1C",
											"_brandtheme2" => "00DB00",
											"_brandratio" => ".25"),
					"rouge" => array("displayname" => "Classic - Rouge",
											"_brandprimary" => "AA0000",
											"_brandtheme1" => "990000",
											"_brandtheme2" => "990000",
											"_brandratio" => ".25"),
					"chromeblue" => array("displayname" => "Classic - Blue",
											"_brandprimary" => "345699",
											"_brandtheme1" => "5764FE",
											"_brandtheme2" => "B2BAFF",
											"_brandratio" => "0"),
					"cherrybubblegum" => array("displayname" => "Classic - BubbleGum",
											"_brandprimary" => "9F0000",
											"_brandtheme1" => "9F0000",
											"_brandtheme2" => "9F0000",
											"_brandratio" => ".2"),
					"chromepurple" => array("displayname" => "Classic - Purple",
											"_brandprimary" => "5D00A4",
											"_brandtheme1" => "7E1DCB",
											"_brandtheme2" => "7B00FA",
											"_brandratio" => ".25"),
					"chromeorange" => array("displayname" => "Classic - Orange",
											"_brandprimary" => "C66000",
											"_brandtheme1" => "B47E1A",
											"_brandtheme2" => "7C1700",
											"_brandratio" => ".25"),

					"grass2" => array("displayname" => "Fun - Grass Fields",
											"_brandprimary" => "000099",
											"_brandtheme1" => "00C222",
											"_brandtheme2" => "22CC22",
											"_brandratio" => ".15"),
					"ocean" => array("displayname" => "Fun - Ocean",
										"_brandprimary" => "346799",
											"_brandtheme1" => "999999",
											"_brandtheme2" => "CCCCCC",
											"_brandratio" => ".3"),
					"marble" => array("displayname" => "Fun - Marble",
											"_brandprimary" => "26477D",
											"_brandtheme1" => "89A3CE",
											"_brandtheme2" => "89A3CE",
											"_brandratio" => ".2"),
					"nature" => array("displayname" => "Fun - Nature",
											"_brandprimary" => "785000",
											"_brandtheme1" => "00CC00",
											"_brandtheme2" => "0c8100",
											"_brandratio" => ".3"),
					"redtheme" =>	array("displayname" => "Fun - Racecar Red",
											"_brandprimary" => "000000",
											"_brandtheme1" => "BE0101",
											"_brandtheme2" => "BE0101",
											"_brandratio" => ".3"),
					"easy_invaders" =>   array("displayname" => "Fun - Space Invaders",
											"_brandprimary" => "000000",
											"_brandtheme1" => "BE0101",
											"_brandtheme2" => "BE0101",
											"_brandratio" => ".2")
					);
?>