<?
//Color schemes.inc.php

$COLORSCHEMES =  array("orangeborder" => array("displayname" => "orangeborder",
											"_brandprimary" => "FF8C00",
											"_brandtheme1" => "B8860B",
											"_brandtheme2" => "DAA520",
											"_brandratio" => ".3"),
					"dodgerblue" => array("displayname" => "dodgerblue",
											"_brandprimary" => "1E90FF",
											"_brandtheme1" => "87CEEB",
											"_brandtheme2" => "1E90FF",
											"_brandratio" => ".3"),
					"redborder" =>	array("displayname" => "redborder",
											"_brandprimary" => "DC143C",
											"_brandtheme1" => "800000",
											"_brandtheme2" => "B22222",
											"_brandratio" => ".3"),
					"greenborder" => array("displayname" => "greenborder",
											"_brandprimary" =>"228B22",
											"_brandtheme1" => "006400",
											"_brandtheme2" => "32CD32",
											"_brandratio" => ".3"),
					"sm" => array("displayname" => "sm",
									"_brandprimary" => "346799",
											"_brandtheme1" => "999999",
											"_brandtheme2" => "CCCCCC",
											"_brandratio" => "0"),
					"clouds" => array("displayname" => "clouds",
										"_brandprimary" => "1E90FF",
											"_brandtheme1" => "1E90FF",
											"_brandtheme2" => "1E90FF",
											"_brandratio" => ".3"),
					"xmas" => array("displayname" => "xmas",
										"_brandprimary" => "00F000",
											"_brandtheme1" => "00F000",
											"_brandtheme2" => "00F000",
											"_brandratio" => ".1"),
					"redmainblueback" => array("displayname" => "redmainblueback",
											"_brandprimary" => "CC0000",
											"_brandtheme1" => "990000",
											"_brandtheme2" => "550000",
											"_brandratio" => ".1"),
					"bluemainblueback" => array("displayname" => "bluemainblueback",
											"_brandprimary" => "0011FF",
											"_brandtheme1" => "0099CC",
											"_brandtheme2" => "0000CC",
											"_brandratio" => ".1"),
					"grass" => array("displayname" => "grass",
											"_brandprimary" => "339933",
											"_brandtheme1" => "00CC00",
											"_brandtheme2" => "0c8100",
											"_brandratio" => ".3"),
					"nature" => array("displayname" => "nature",
											"_brandprimary" => "0070D2",
											"_brandtheme1" => "00CC00",
											"_brandtheme2" => "0c8100",
											"_brandratio" => ".15"),
					"rouge" => array("displayname" => "rouge",
											"_brandprimary" => "AA0000",
											"_brandtheme1" => "990000",
											"_brandtheme2" => "990000",
											"_brandratio" => ".25"),
					"grass2" => array("displayname" => "grass2",
											"_brandprimary" => "000099",
											"_brandtheme1" => "00C222",
											"_brandtheme2" => "22CC22",
											"_brandratio" => ".15"),
					"ocean" => array("displayname" => "ocean",
										"_brandprimary" => "346799",
											"_brandtheme1" => "999999",
											"_brandtheme2" => "CCCCCC",
											"_brandratio" => "0"),
					"chromeblue" => array("displayname" => "chromeblue",
											"_brandprimary" => "345699",
											"_brandtheme1" => "5764FE",
											"_brandtheme2" => "B2BAFF",
											"_brandratio" => "0"),
					"cherrybubblegum" => array("displayname" => "Cherry BubbleGum",
											"_brandprimary" => "9F0000",
											"_brandtheme1" => "9F0000",
											"_brandtheme2" => "9F0000",
											"_brandratio" => ".2"),
					"mintgreen" => array("displayname" => "mintgreen",
											"_brandprimary" => "009900",
											"_brandtheme1" => "1CBF1C",
											"_brandtheme2" => "00DB00",
											"_brandratio" => ".25"),
					"chromepurple" => array("displayname" => "chromepurple",
											"_brandprimary" => "5D00A4",
											"_brandtheme1" => "7E1DCB",
											"_brandtheme2" => "7B00FA",
											"_brandratio" => ".25"),
					"chromeorange" => array("displayname" => "chromeorange",
											"_brandprimary" => "C66000",
											"_brandtheme1" => "B47E1A",
											"_brandtheme2" => "7C1700",
											"_brandratio" => ".25"),
					"bluetheme2" => array("displayname" => "Blue Theme 2",
											"_brandprimary" => "26477D",
											"_brandtheme1" => "89A3CE",
											"_brandtheme2" => "89A3CE",
											"_brandratio" => ".5"),
					"rose" =>	array("displayname" => "Rose",
											"_brandprimary" => "740606",
											"_brandtheme1" => "BE0101",
											"_brandtheme2" => "BE0101",
											"_brandratio" => ".5"),
					"gold" =>	array("displayname" => "Gold",
											"_brandprimary" => "654000",
											"_brandtheme1" => "E9B500",
											"_brandtheme2" => "E9B500",
											"_brandratio" => ".5"),
					"lemon" =>	array("displayname" => "Lemon",
											"_brandprimary" => "654000",
											"_brandtheme1" => "E9B500",
											"_brandtheme2" => "E9B500",
											"_brandratio" => ".5"),
					"tangerine" =>	array("displayname" => "Tangerine",
											"_brandprimary" => "291300",
											"_brandtheme1" => "FE8C0D",
											"_brandtheme2" => "FE8C0D",
											"_brandratio" => ".5"),
					"greentheme" => array("displayname" => "Green Theme",
											"_brandprimary" =>"42563B",
											"_brandtheme1" => "006400",
											"_brandtheme2" => "32CD32",
											"_brandratio" => ".3"),
					"chrome" => array("displayname" => "Chrome",
											"_brandprimary" => "000000",
											"_brandtheme1" => "6F7177",
											"_brandtheme2" => "6F7177",
											"_brandratio" => ".3")
					);
?>