<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';

include_once $GLOBALS['THRIFT_ROOT'].'/packages/commsuite/commsuite_types.php';

interface CommSuiteIf {
  public function emailMessagePreviewForPriority($sessionid, $messageid, $jobpriority);
  public function emailMessageViewForJobPerson($sessionid, $messageid, $jobid, $personid);
  public function audioFileGetForFormat($sessionid, $contentid, $format);
  public function ttsGetForTextLanguageGenderFormat($sessionid, $text, $language, $gender, $format);
}

class CommSuiteClient implements CommSuiteIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function emailMessagePreviewForPriority($sessionid, $messageid, $jobpriority)
  {
    $this->send_emailMessagePreviewForPriority($sessionid, $messageid, $jobpriority);
    return $this->recv_emailMessagePreviewForPriority();
  }

  public function send_emailMessagePreviewForPriority($sessionid, $messageid, $jobpriority)
  {
    $args = new commsuite_CommSuite_emailMessagePreviewForPriority_args();
    $args->sessionid = $sessionid;
    $args->messageid = $messageid;
    $args->jobpriority = $jobpriority;
    $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'emailMessagePreviewForPriority', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('emailMessagePreviewForPriority', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_emailMessagePreviewForPriority()
  {
    $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, 'commsuite_CommSuite_emailMessagePreviewForPriority_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new commsuite_CommSuite_emailMessagePreviewForPriority_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new Exception("emailMessagePreviewForPriority failed: unknown result");
  }

  public function emailMessageViewForJobPerson($sessionid, $messageid, $jobid, $personid)
  {
    $this->send_emailMessageViewForJobPerson($sessionid, $messageid, $jobid, $personid);
    return $this->recv_emailMessageViewForJobPerson();
  }

  public function send_emailMessageViewForJobPerson($sessionid, $messageid, $jobid, $personid)
  {
    $args = new commsuite_CommSuite_emailMessageViewForJobPerson_args();
    $args->sessionid = $sessionid;
    $args->messageid = $messageid;
    $args->jobid = $jobid;
    $args->personid = $personid;
    $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'emailMessageViewForJobPerson', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('emailMessageViewForJobPerson', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_emailMessageViewForJobPerson()
  {
    $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, 'commsuite_CommSuite_emailMessageViewForJobPerson_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new commsuite_CommSuite_emailMessageViewForJobPerson_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new Exception("emailMessageViewForJobPerson failed: unknown result");
  }

  public function audioFileGetForFormat($sessionid, $contentid, $format)
  {
    $this->send_audioFileGetForFormat($sessionid, $contentid, $format);
    return $this->recv_audioFileGetForFormat();
  }

  public function send_audioFileGetForFormat($sessionid, $contentid, $format)
  {
    $args = new commsuite_CommSuite_audioFileGetForFormat_args();
    $args->sessionid = $sessionid;
    $args->contentid = $contentid;
    $args->format = $format;
    $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'audioFileGetForFormat', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('audioFileGetForFormat', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_audioFileGetForFormat()
  {
    $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, 'commsuite_CommSuite_audioFileGetForFormat_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new commsuite_CommSuite_audioFileGetForFormat_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new Exception("audioFileGetForFormat failed: unknown result");
  }

  public function ttsGetForTextLanguageGenderFormat($sessionid, $text, $language, $gender, $format)
  {
    $this->send_ttsGetForTextLanguageGenderFormat($sessionid, $text, $language, $gender, $format);
    return $this->recv_ttsGetForTextLanguageGenderFormat();
  }

  public function send_ttsGetForTextLanguageGenderFormat($sessionid, $text, $language, $gender, $format)
  {
    $args = new commsuite_CommSuite_ttsGetForTextLanguageGenderFormat_args();
    $args->sessionid = $sessionid;
    $args->text = $text;
    $args->language = $language;
    $args->gender = $gender;
    $args->format = $format;
    $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'ttsGetForTextLanguageGenderFormat', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('ttsGetForTextLanguageGenderFormat', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_ttsGetForTextLanguageGenderFormat()
  {
    $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, 'commsuite_CommSuite_ttsGetForTextLanguageGenderFormat_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new commsuite_CommSuite_ttsGetForTextLanguageGenderFormat_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new Exception("ttsGetForTextLanguageGenderFormat failed: unknown result");
  }

}

// HELPER FUNCTIONS AND STRUCTURES

class commsuite_CommSuite_emailMessagePreviewForPriority_args {
  static $_TSPEC;

  public $sessionid = null;
  public $messageid = null;
  public $jobpriority = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'sessionid',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'messageid',
          'type' => TType::I32,
          ),
        3 => array(
          'var' => 'jobpriority',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['sessionid'])) {
        $this->sessionid = $vals['sessionid'];
      }
      if (isset($vals['messageid'])) {
        $this->messageid = $vals['messageid'];
      }
      if (isset($vals['jobpriority'])) {
        $this->jobpriority = $vals['jobpriority'];
      }
    }
  }

  public function getName() {
    return 'CommSuite_emailMessagePreviewForPriority_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->sessionid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->messageid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->jobpriority);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CommSuite_emailMessagePreviewForPriority_args');
    if ($this->sessionid !== null) {
      $xfer += $output->writeFieldBegin('sessionid', TType::STRING, 1);
      $xfer += $output->writeString($this->sessionid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->messageid !== null) {
      $xfer += $output->writeFieldBegin('messageid', TType::I32, 2);
      $xfer += $output->writeI32($this->messageid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->jobpriority !== null) {
      $xfer += $output->writeFieldBegin('jobpriority', TType::I32, 3);
      $xfer += $output->writeI32($this->jobpriority);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class commsuite_CommSuite_emailMessagePreviewForPriority_result {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::STRUCT,
          'class' => 'commsuite_EmailMessageView',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'CommSuite_emailMessagePreviewForPriority_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::STRUCT) {
            $this->success = new commsuite_EmailMessageView();
            $xfer += $this->success->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CommSuite_emailMessagePreviewForPriority_result');
    if ($this->success !== null) {
      if (!is_object($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
      $xfer += $this->success->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class commsuite_CommSuite_emailMessageViewForJobPerson_args {
  static $_TSPEC;

  public $sessionid = null;
  public $messageid = null;
  public $jobid = null;
  public $personid = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'sessionid',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'messageid',
          'type' => TType::I32,
          ),
        3 => array(
          'var' => 'jobid',
          'type' => TType::I32,
          ),
        4 => array(
          'var' => 'personid',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['sessionid'])) {
        $this->sessionid = $vals['sessionid'];
      }
      if (isset($vals['messageid'])) {
        $this->messageid = $vals['messageid'];
      }
      if (isset($vals['jobid'])) {
        $this->jobid = $vals['jobid'];
      }
      if (isset($vals['personid'])) {
        $this->personid = $vals['personid'];
      }
    }
  }

  public function getName() {
    return 'CommSuite_emailMessageViewForJobPerson_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->sessionid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->messageid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->jobid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->personid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CommSuite_emailMessageViewForJobPerson_args');
    if ($this->sessionid !== null) {
      $xfer += $output->writeFieldBegin('sessionid', TType::STRING, 1);
      $xfer += $output->writeString($this->sessionid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->messageid !== null) {
      $xfer += $output->writeFieldBegin('messageid', TType::I32, 2);
      $xfer += $output->writeI32($this->messageid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->jobid !== null) {
      $xfer += $output->writeFieldBegin('jobid', TType::I32, 3);
      $xfer += $output->writeI32($this->jobid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->personid !== null) {
      $xfer += $output->writeFieldBegin('personid', TType::I32, 4);
      $xfer += $output->writeI32($this->personid);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class commsuite_CommSuite_emailMessageViewForJobPerson_result {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::STRUCT,
          'class' => 'commsuite_EmailMessageView',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'CommSuite_emailMessageViewForJobPerson_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::STRUCT) {
            $this->success = new commsuite_EmailMessageView();
            $xfer += $this->success->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CommSuite_emailMessageViewForJobPerson_result');
    if ($this->success !== null) {
      if (!is_object($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
      $xfer += $this->success->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class commsuite_CommSuite_audioFileGetForFormat_args {
  static $_TSPEC;

  public $sessionid = null;
  public $contentid = null;
  public $format = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'sessionid',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'contentid',
          'type' => TType::I64,
          ),
        3 => array(
          'var' => 'format',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['sessionid'])) {
        $this->sessionid = $vals['sessionid'];
      }
      if (isset($vals['contentid'])) {
        $this->contentid = $vals['contentid'];
      }
      if (isset($vals['format'])) {
        $this->format = $vals['format'];
      }
    }
  }

  public function getName() {
    return 'CommSuite_audioFileGetForFormat_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->sessionid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->contentid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->format);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CommSuite_audioFileGetForFormat_args');
    if ($this->sessionid !== null) {
      $xfer += $output->writeFieldBegin('sessionid', TType::STRING, 1);
      $xfer += $output->writeString($this->sessionid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->contentid !== null) {
      $xfer += $output->writeFieldBegin('contentid', TType::I64, 2);
      $xfer += $output->writeI64($this->contentid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->format !== null) {
      $xfer += $output->writeFieldBegin('format', TType::STRING, 3);
      $xfer += $output->writeString($this->format);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class commsuite_CommSuite_audioFileGetForFormat_result {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::STRUCT,
          'class' => 'commsuite_FileData',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'CommSuite_audioFileGetForFormat_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::STRUCT) {
            $this->success = new commsuite_FileData();
            $xfer += $this->success->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CommSuite_audioFileGetForFormat_result');
    if ($this->success !== null) {
      if (!is_object($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
      $xfer += $this->success->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class commsuite_CommSuite_ttsGetForTextLanguageGenderFormat_args {
  static $_TSPEC;

  public $sessionid = null;
  public $text = null;
  public $language = null;
  public $gender = null;
  public $format = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'sessionid',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'text',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'language',
          'type' => TType::STRING,
          ),
        4 => array(
          'var' => 'gender',
          'type' => TType::STRING,
          ),
        5 => array(
          'var' => 'format',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['sessionid'])) {
        $this->sessionid = $vals['sessionid'];
      }
      if (isset($vals['text'])) {
        $this->text = $vals['text'];
      }
      if (isset($vals['language'])) {
        $this->language = $vals['language'];
      }
      if (isset($vals['gender'])) {
        $this->gender = $vals['gender'];
      }
      if (isset($vals['format'])) {
        $this->format = $vals['format'];
      }
    }
  }

  public function getName() {
    return 'CommSuite_ttsGetForTextLanguageGenderFormat_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->sessionid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->text);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->language);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->gender);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->format);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CommSuite_ttsGetForTextLanguageGenderFormat_args');
    if ($this->sessionid !== null) {
      $xfer += $output->writeFieldBegin('sessionid', TType::STRING, 1);
      $xfer += $output->writeString($this->sessionid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->text !== null) {
      $xfer += $output->writeFieldBegin('text', TType::STRING, 2);
      $xfer += $output->writeString($this->text);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->language !== null) {
      $xfer += $output->writeFieldBegin('language', TType::STRING, 3);
      $xfer += $output->writeString($this->language);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->gender !== null) {
      $xfer += $output->writeFieldBegin('gender', TType::STRING, 4);
      $xfer += $output->writeString($this->gender);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->format !== null) {
      $xfer += $output->writeFieldBegin('format', TType::STRING, 5);
      $xfer += $output->writeString($this->format);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class commsuite_CommSuite_ttsGetForTextLanguageGenderFormat_result {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::STRUCT,
          'class' => 'commsuite_FileData',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'CommSuite_ttsGetForTextLanguageGenderFormat_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::STRUCT) {
            $this->success = new commsuite_FileData();
            $xfer += $this->success->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('CommSuite_ttsGetForTextLanguageGenderFormat_result');
    if ($this->success !== null) {
      if (!is_object($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
      $xfer += $this->success->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

?>
